---
version: '3.2'

networks:
  rservenet:

services:
  rserve:
    build: 
      context: .
    image: labkey/rserve
    user: "${UID:-0}:${GID:-0}"
    ports:
      - "6311:6311"
    volumes:
      - "$CATALINA_HOME/temp/reports_temp:/volumes/reports_temp"
      - "$LABKEY_HOME/build/deploy/files:/volumes/data"
    networks:
      rservenet:
        aliases:
        - rserve
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"
