---
version: '2'

networks:
  rservenet:

services:
  rserve:
    build:
      context: .
    image: labkey/rserve
    ports:
      - "6311:6311"
    volumes:
      - "$CATALINA_HOME/temp/reports_temp:/volumes/reports_temp"
      - "$LABKEY_HOME/build/deploy/files:/volumes/data"
    networks:
      rservenet:
        aliases:
        - rserve
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"

environment:
  - CATALINA_HOME=$CATALINA_HOME
  - LABKEY_HOME=$LABKEY_HOME